name: Corretor de Exercícios

on:
  push:
  workflow_dispatch:

jobs:
  aula01:
    name: aula01
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 3-bimestre/orientacao-a-objetos/aula01
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm test

  aula02:
    name: aula02
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 3-bimestre/orientacao-a-objetos/aula02
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm test

  aula03:
    name: aula03
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 3-bimestre/orientacao-a-objetos/aula03
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm test

  aula04:
    name: aula04
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 3-bimestre/orientacao-a-objetos/aula04
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm test

  aula07:
    name: aula07
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 3-bimestre/orientacao-a-objetos/aula07
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm test

  aula08:
    name: aula08
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 3-bimestre/orientacao-a-objetos/aula08
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm test

  aula09:
    name: aula09
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 3-bimestre/orientacao-a-objetos/aula09
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm test

  aula10:
    name: aula10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 3-bimestre/orientacao-a-objetos/aula10
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm test

  aula12:
    name: aula12
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 3-bimestre/orientacao-a-objetos/aula12
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm test

  aula16:
    name: aula16
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 3-bimestre/orientacao-a-objetos/aula16
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm test