name: Detectar aluno

on:
  push:

jobs:
  aluno:
    runs-on: ubuntu-latest

    steps:
      - name: Identificar aluno
        run: |
          echo "Repositório: ${{ github.repository }}"
          echo "Usuário: ${{ github.repository_owner }}"
