name: Corretor de Projetos Nível 2

on:
  push:
  workflow_dispatch:

jobs:
  projeto1-desenvolvimento-de-pagina-institucional-em-html:
    name: projeto1-desenvolvimento-de-pagina-institucional-em-html
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 1-bimestre/programacao-web/projetos/projeto1-desenvolvimento-de-pagina-institucional-em-html
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  projeto2-sistema-de-cadastro-e-listagem-de-alunos:
    name: projeto2-sistema-de-cadastro-e-listagem-de-alunos
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 1-bimestre/programacao-web/projetos/projeto2-sistema-de-cadastro-e-listagem-de-alunos
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  projeto3-pagina-de-perfil-profissional:
    name: projeto3-pagina-de-perfil-profissional
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 1-bimestre/programacao-web/projetos/projeto3-pagina-de-perfil-profissional
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  projeto4-sistema-de-lista-de-tarefas:
    name: projeto4-sistema-de-lista-de-tarefas
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 1-bimestre/programacao-web/projetos/projeto4-sistema-de-lista-de-tarefas
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  projeto5-primeiro-site-com-react:
    name: projeto5-primeiro-site-com-react
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 2-bimestre/programacao-web/projetos/projeto5-primeiro-site-com-react/nivel2/react
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test