name: Corretor de Projetos Nível 1

on:
  push:
  workflow_dispatch:

jobs:
  projeto5-primeiro-site-com-react:
    name: projeto5-primeiro-site-com-react
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 2-bimestre/programacao-web/projetos/projeto5-primeiro-site-com-react/nivel1
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test