name: Corretor de Projetos

on:
  push:
  workflow_dispatch:

jobs:
  projeto1:
    name: projeto1
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 3-bimestre/orientacao-a-objetos/projetos/projeto1
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm test

  projeto2:
    name: projeto2
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 3-bimestre/orientacao-a-objetos/projetos/projeto2
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm test

  projeto3:
    name: projeto3
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 3-bimestre/orientacao-a-objetos/projetos/projeto3
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm test