name: Corretor de Exercícios

on:
  push:
  workflow_dispatch:

jobs:
  ex01-primeira-pagina-html:
    name: ex01-primeira-pagina-html
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 1-bimestre/programacao-web/ex01-primeira-pagina-html
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  ex02-pagina-com-texto-formatado:
    name: ex02-pagina-com-texto-formatado
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 1-bimestre/programacao-web/ex02-pagina-com-texto-formatado
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  ex03-pagina-com-imagem-e-link:
    name: ex03-pagina-com-imagem-e-link
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 1-bimestre/programacao-web/ex03-pagina-com-imagem-e-link
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  ex04-pagina-organizada-com-listas:
    name: ex04-pagina-organizada-com-listas
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 1-bimestre/programacao-web/ex04-pagina-organizada-com-listas
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  ex05-criando-tabelas:
    name: ex05-criando-tabelas
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 1-bimestre/programacao-web/ex05-criando-tabelas
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  ex06-criando-formularios:
    name: ex06-criando-formularios
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 1-bimestre/programacao-web/ex06-criando-formularios
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  ex07-criando-site-com-css:
    name: ex07-criando-site-com-css
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 1-bimestre/programacao-web/ex07-criando-site-com-css
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  ex08-site-com-box-model:
    name: ex08-site-com-box-model
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 1-bimestre/programacao-web/ex08-site-com-box-model
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  ex09-trabalhando-com-seletores:
    name: ex09-trabalhando-com-seletores
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 1-bimestre/programacao-web/ex09-trabalhando-com-seletores
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  ex10-site-com-display:
    name: ex10-site-com-display
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 1-bimestre/programacao-web/ex10-site-com-display
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  ex11-aprendendo-dom:
    name: ex11-aprendendo-dom
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 1-bimestre/programacao-web/ex11-aprendendo-dom
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  ex12-criando-elementos:
    name: ex12-criando-elementos
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 1-bimestre/programacao-web/ex12-criando-elementos
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  ex13-manipulando-dom:
    name: ex13-manipulando-dom
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 1-bimestre/programacao-web/ex13-manipulando-dom
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  ex14-enviando-valores-do-dom:
    name: ex14-enviando-valores-do-dom
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 1-bimestre/programacao-web/ex14-enviando-valores-do-dom
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  ex15-trabalhando-com-eventos:
    name: ex15-trabalhando-com-eventos
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 1-bimestre/programacao-web/ex15-trabalhando-com-eventos
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  ex16-manipulando-estilos:
    name: ex16-manipulando-estilos
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 1-bimestre/programacao-web/ex16-manipulando-estilos
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test