name: Corretor de Exercícios 2º BI

on:
  push:
  workflow_dispatch:

jobs:
  aula02-primeira-pagina-com-react-e-conhecendo-o-jsx:
    name: aula02-primeira-pagina-com-react-e-conhecendo-o-jsx
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 2-bimestre/programacao-web/aula02-primeira-pagina-com-react-e-conhecendo-o-jsx
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  aula03-criando-um-projeto-com-vite:
    name: aula03-criando-um-projeto-com-vite
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 2-bimestre/programacao-web/aula03-criando-um-projeto-com-vite/react
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  aula04-criando-primeiros-componentes:
    name: aula04-criando-primeiros-componentes
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 2-bimestre/programacao-web/aula04-criando-primeiros-componentes/react
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  aula05-criando-um-componente-perfil-dinamico:
    name: aula05-criando-um-componente-perfil-dinamico
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 2-bimestre/programacao-web/aula05-criando-um-componente-perfil-dinamico/react
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  aula06-criando-e-estilizando-um-footer:
    name: aula06-criando-e-estilizando-um-footer
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 2-bimestre/programacao-web/aula06-criando-e-estilizando-um-footer/react
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  aula07-criando-um-componente-filme:
    name: aula07-criando-um-componente-filme
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 2-bimestre/programacao-web/aula07-criando-um-componente-filme/react
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  aula08-criando-um-componente-aluno:
    name: aula08-criando-um-componente-aluno
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 2-bimestre/programacao-web/aula08-criando-um-componente-aluno/react
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  aula09-criando-componente-painel:
    name: aula09-criando-componente-painel
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 2-bimestre/programacao-web/aula09-criando-componente-painel/react
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  aula10-criando-componente-input:
    name: aula10-criando-componente-input
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 2-bimestre/programacao-web/aula10-criando-componente-input/react
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test