name: Corretor de Projetos Nível 1

on:
  push:
  workflow_dispatch:

jobs:
  projeto5-primeiro-site-com-react:
    name: projeto5-primeiro-site-com-react
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 2-bimestre/programacao-web/projetos/projeto5-primeiro-site-com-react/nivel1
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  projeto6-componente-profile:
    name: projeto6-componente-profile
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 2-bimestre/programacao-web/projetos/projeto6-componente-profile/nivel1
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  projeto7-painel-de-acoes-rpg:
    name: projeto7-painel-de-acoes-rpg
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 2-bimestre/programacao-web/projetos/projeto7-painel-de-acoes-rpg/nivel1
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test